### Loading the `.json` format of Steam Games Dataset and converting to the `.csv` format

In [11]:
import numpy as np
import pandas as pd

json_path = "./games.json"

In [12]:
def convert_dict_to_string(dict_object):
    if not dict_object:
        return np.nan
    return ",".join(dict_object.keys())


def convert_list_to_string(entries):
    if not entries:
        return np.nan
    return ",".join(entries)


def read_convert_json_dataset():
    _df = pd.read_json(json_path)
    _df = _df.T
    _df['AppID'] = _df.index

    for col in _df.columns.values:
        sample = _df.loc[546560, col]

        if isinstance(sample, dict):
            _df[col] = _df[col].apply(
                lambda x: convert_dict_to_string(x)
                if isinstance(x, dict) else x
            )

        elif isinstance(sample, list):
            if not sample or isinstance(sample[0], str):
                _df[col] = _df[col].apply(
                    lambda x: convert_list_to_string(x)
                    if isinstance(x, list) else x
                )

    _df = _df.reset_index(drop=True).set_index("AppID")
    return _df


df = read_convert_json_dataset()

Remove empty lists from the `tags` and `packages` columns and replace them with NaN values.

In [22]:
df["tags"] = df["tags"].apply(
    lambda x: np.nan if isinstance(x, list) and len(x) == 0 else x
)
df["packages"] = df["packages"].apply(
    lambda x: np.nan if isinstance(x, list) and len(x) == 0 else x
)

#### All columns should now be converted:

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144499 entries, 2539430 to 5167030
Data columns (total 42 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      144499 non-null  object
 1   release_date              144499 non-null  object
 2   required_age              144499 non-null  object
 3   price                     144499 non-null  object
 4   dlc_count                 144499 non-null  object
 5   detailed_description      144499 non-null  object
 6   about_the_game            144499 non-null  object
 7   short_description         144499 non-null  object
 8   reviews                   144499 non-null  object
 9   header_image              144499 non-null  object
 10  website                   144499 non-null  object
 11  support_url               144499 non-null  object
 12  support_email             144499 non-null  object
 13  windows                   144499 non-null  object
 14  mac                       144499 non-null  object
 15  linux                     144499 non-null  object
 16  metacritic_score          144499 non-null  object
 17  metacritic_url            144499 non-null  object
 18  achievements              144499 non-null  object
 19  recommendations           144499 non-null  object
 20  notes                     144499 non-null  object
 21  supported_languages       136098 non-null  object
 22  full_audio_languages      58220 non-null   object
 23  packages                  144499 non-null  object
 24  developers                136045 non-null  object
 25  publishers                135646 non-null  object
 26  categories                135520 non-null  object
 27  genres                    136063 non-null  object
 28  screenshots               138461 non-null  object
 29  movies                    0 non-null       float64
 30  user_score                144499 non-null  object
 31  score_rank                144499 non-null  object
 32  positive                  144499 non-null  object
 33  negative                  144499 non-null  object
 34  estimated_owners          144499 non-null  object
 35  average_playtime_forever  144499 non-null  object
 36  average_playtime_2weeks   144499 non-null  object
 37  median_playtime_forever   144499 non-null  object
 38  median_playtime_2weeks    144499 non-null  object
 39  discount                  144499 non-null  object
 40  peak_ccu                  144499 non-null  object
 41  tags                      83385 non-null   object
dtypes: float64(1), object(41)
memory usage: 47.4+ MB

In [14]:
df.head()

,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,header_image,...,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags
AppID,,,,,,,,,,,,,,,,,,,,,
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0,0.0,0,,,,,https://shared.akamai.steamstatic.com/store_it...,...,0,0,0 - 0,0,0,0,0,0,0,[]
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0,5.24,0,"Springtime, April: when the cherry trees come ...","Springtime, April: when the cherry trees come ...","Spring has come, and our protagonist, Yukinari...",,https://shared.akamai.steamstatic.com/store_it...,...,252,3,0 - 20000,8,0,8,0,65,0,"Adventure,Visual Novel,Anime,Cute"
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0,4.99,0,"Immerse yourself in the most beloved, mystical...","Immerse yourself in the most beloved, mystical...",Discover an entrancing and spectacular world!,,https://shared.akamai.steamstatic.com/store_it...,...,21,3,0 - 20000,0,0,0,0,0,0,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec..."
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",Yuha! I'll start the broadcast! Hakko's extrem...,,https://shared.akamai.steamstatic.com/store_it...,...,0,0,0 - 20000,0,0,0,0,0,1,[]
3631080,Maze Quest VR,"Apr 24, 2025",0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,,https://shared.akamai.steamstatic.com/store_it...,...,0,0,0 - 20000,0,0,0,0,0,0,[]

In [23]:
df.to_csv("steam_games.csv", na_rep="") # Saving the converted dataframe

,AppID,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0,0.00,0,NaN,NaN,NaN,NaN,...,0,0,0 - 0,0,0,0,0,0,0,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0,5.24,0,"Springtime, April: when the cherry trees come ...","Springtime, April: when the cherry trees come ...","Spring has come, and our protagonist, Yukinari...",NaN,...,252,3,0 - 20000,8,0,8,0,65,0,"Adventure,Visual Novel,Anime,Cute"
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0,4.99,0,"Immerse yourself in the most beloved, mystical...","Immerse yourself in the most beloved, mystical...",Discover an entrancing and spectacular world!,NaN,...,21,3,0 - 20000,0,0,0,0,0,0,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",Yuha! I'll start the broadcast! Hakko's extrem...,NaN,...,0,0,0 - 20000,0,0,0,0,0,1,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,NaN,...,0,0,0 - 20000,0,0,0,0,0,0,NaN