# Data Summary

This notebook provides a summary of the Steam Games dataset.

## 1. Import Libraries and Load the Dataset

In [1]:
import numpy as np
import pandas as pd

dataset = pd.read_csv('steam_games.csv')

## 2. Dataset Overview
### 2.1 Shape of the Dataset

In [2]:
print(f"Dataset Shape: {dataset.shape}")
print(f"Number of Columns: {dataset.shape[1]}")
print(f"Number of Rows: {dataset.shape[0]}")

Dataset Shape: (141900, 43)
Number of Columns: 43
Number of Rows: 141900

### 2.2 Column Names

In [16]:
print("Column Names")
for col in dataset.columns:
    print(f"- {col}")

Column Names
- AppID
- name
- release_date
- required_age
- price
- dlc_count
- detailed_description
- about_the_game
- short_description
- reviews
- header_image
- website
- support_url
- support_email
- windows
- mac
- linux
- metacritic_score
- metacritic_url
- achievements
- recommendations
- notes
- supported_languages
- full_audio_languages
- packages
- developers
- publishers
- categories
- genres
- screenshots
- movies
- user_score
- score_rank
- positive
- negative
- estimated_owners
- average_playtime_forever
- average_playtime_2weeks
- median_playtime_forever
- median_playtime_2weeks
- discount
- peak_ccu
- tags

### 2.3 Data Types

In [15]:
print("Data Types")
dataset.dtypes

Data Types

AppID                         int64
name                         object
release_date                 object
required_age                  int64
price                       float64
dlc_count                     int64
detailed_description         object
about_the_game               object
short_description            object
reviews                      object
header_image                 object
website                      object
support_url                  object
support_email                object
windows                        bool
mac                            bool
linux                          bool
metacritic_score              int64
metacritic_url               object
achievements                  int64
recommendations               int64
notes                        object
supported_languages          object
full_audio_languages         object
packages                     object
developers                   object
publishers                   object
categories                   object
genres                       object
screenshots                  object
movies                      float64
user_score                    int64
score_rank                  float64
positive                      int64
negative                      int64
estimated_owners             object
average_playtime_forever      int64
average_playtime_2weeks       int64
median_playtime_forever       int64
median_playtime_2weeks        int64
discount                      int64
peak_ccu                      int64
tags                         object
dtype: object

### 2.4 Missing Values

In [12]:
print("Missing Values")
missing_values = dataset.isnull().sum()
missing_values[missing_values > 0]

Missing Values

name                         2
detailed_description      8485
about_the_game            8516
short_description         8332
reviews                 129300
header_image                86
website                  87020
support_url              80967
support_email            24315
metacritic_url          137624
notes                   114915
supported_languages       8400
full_audio_languages     84608
packages                 28180
developers                8461
publishers                8944
categories                8977
genres                    8435
screenshots               6037
movies                  141900
score_rank              141860
tags                     58521
dtype: int64

### 2.5 Example Rows

In [8]:
print("Example Rows")
dataset.head()

Example Rows

,AppID,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0,0.00,0,NaN,NaN,NaN,NaN,...,0,0,0 - 0,0,0,0,0,0,0,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0,5.24,0,"Springtime, April: when the cherry trees come ...","Springtime, April: when the cherry trees come ...","Spring has come, and our protagonist, Yukinari...",NaN,...,252,3,0 - 20000,8,0,8,0,65,0,"Adventure,Visual Novel,Anime,Cute"
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0,4.99,0,"Immerse yourself in the most beloved, mystical...","Immerse yourself in the most beloved, mystical...",Discover an entrancing and spectacular world!,NaN,...,21,3,0 - 20000,0,0,0,0,0,0,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",Yuha! I'll start the broadcast! Hakko's extrem...,NaN,...,0,0,0 - 20000,0,0,0,0,0,1,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,NaN,...,0,0,0 - 20000,0,0,0,0,0,0,NaN

## 3. Summary Statistics
### 3.1 Numerical Columns

In [11]:
print("Summary Statistics for Numerical Columns")
numerical_summary = dataset.describe()
numerical_summary

Summary Statistics for Numerical Columns

,AppID,required_age,price,dlc_count,metacritic_score,achievements,recommendations,movies,user_score,score_rank,positive,negative,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu
count,1.419000e+05,141900.000000,141900.000000,141900.000000,141900.000000,141900.000000,1.419000e+05,0.0,141900.000000,40.000000,1.419000e+05,1.419000e+05,1.419000e+05,141900.000000,1.419000e+05,141900.000000,141900.000000,1.419000e+05
mean,2.280040e+06,0.151536,4.984797,0.501994,2.227160,17.488562,8.366615e+02,NaN,0.021212,99.175000,9.031312e+02,1.462657e+02,1.800283e+02,12.142382,1.502585e+02,12.976152,16.003763,4.717357e+01
std,1.285513e+06,1.573053,12.440469,13.554325,12.760273,131.746807,2.034151e+04,NaN,1.296659,0.675107,2.611516e+04,4.996354e+03,1.042766e+04,251.580853,1.041351e+04,274.107214,27.531012,3.466766e+03
min,1.000000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,98.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
25%,1.185385e+06,0.000000,0.690000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,99.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
50%,2.186860e+06,0.000000,2.690000,0.000000,0.000000,3.000000,0.000000e+00,NaN,0.000000,99.000000,2.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
75%,3.297130e+06,0.000000,5.990000,0.000000,0.000000,19.000000,0.000000e+00,NaN,0.000000,100.000000,2.600000e+01,7.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,30.000000,0.000000e+00
max,5.201280e+06,21.000000,999.990000,3703.000000,97.000000,9821.000000,4.830455e+06,NaN,100.000000,100.000000,7.642084e+06,1.173003e+06,3.429544e+06,20088.000000,3.429544e+06,20088.000000,100.000000,1.013936e+06

### 3.2 Categorical Columns

In [17]:
print("Summary Statistics for Categorical Columns")
categorical_summary = dataset.describe(include=['object'])
categorical_summary

Summary Statistics for Categorical Columns

,name,release_date,detailed_description,about_the_game,short_description,reviews,header_image,website,support_url,support_email,...,supported_languages,full_audio_languages,packages,developers,publishers,categories,genres,screenshots,estimated_owners,tags
count,141898,141900,133415,133384,133568,12600,141814,54880,60933,117585,...,133500,57292,113720,133439,132956,132923,133465,135863,141900,83379
unique,140467,5338,132767,132722,132122,12392,141704,43842,40149,71767,...,22875,4233,113586,83500,74605,19002,3014,135753,14,77210
top,Shadow of the Tomb Raider: Definitive Edition,"Jun 23, 2026",Help the beautiful girls to immerse themselves...,Help the beautiful girls to immerse themselves...,"This is a casual puzzle game, where the positi...","“🏆 I loved! ❤️❤️❤️” Player “🏆 Cute kittens, ea...",https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,info@bigfishgames.com,...,English,English,[{'title': 'Buy Shadow of the Tomb Raider: Def...,EroticGamesClub,BFG Entertainment,"Single-player,Family Sharing","Casual,Indie",https://shared.akamai.steamstatic.com/store_it...,0 - 20000,"Adventure,Casual,Hidden Object"
freq,20,190,65,65,56,52,20,274,338,323,...,63006,28858,20,239,554,25990,8114,20,77328,273